### ISSUE TITLE
Lists aren't updated after a while

### ISSUE THREAD

**Issue by Makiah** [Makiah/WunderlistTasksWidget#2]
I've noticed that after a while the Übersicht debug console starts to say this, pretty sure it's an access_token bug (I'll look into fixing it).  
![image](https://user-images.githubusercontent.com/10727824/33750155-fef1094c-db9f-11e7-8e72-d193b29410ce.png)

**Comment by letsgorocket** [comment]
Hi Makiah, 
Thank you for developing the widgets! I have problem after move "Wunderlist Tasks Widget" to Widget folder. It pop-up a safari link but I failed to open the link. Do you happen to know how to deal with this error? 
<img width="837" alt="screen shot 2018-01-17 at 2 07 53 pm" src="https://user-images.githubusercontent.com/25697115/35064546-175d8c3e-fb90-11e7-82f2-7c791d6379de.png">

**Comment by Makiah** [comment]
That's an odd issue: it's trying to redirect to the local server to retrieve the authentication token, but it must have not been started yet.  Just to confirm, did you download the zip file included in this repository instead of cloning the repository itself?

**Comment by letsgorocket** [comment]
Thank you for the reply!
Yes, I downloaded "WunderlistTasksWidget.zip" and moved it into Widget folder. I didn't download  "Source code (zip)" and "Source code (tar.gz)".

**Comment by Makiah** [comment]
Huh, that's odd... I suspect it's an issue with node not being installed, have you installed it via Brew?  I'll look into whether I can provide a node binary pre-packaged if that's the case for ease of use.

**Comment by Makiah** [comment]
Seems fixed by bb97755.

**Comment by Makiah** [comment]
Turns out that it actually was a bug which I just fixed, the script was trying to use Node 8.9.0 regardless of whether it existed.  It now uses whichever version is available.
