### ISSUE TITLE
Wunderlist fails to connect

### ISSUE THREAD

**Issue by Kamorini** [Makiah/WunderlistTasksWidget#3]
I continue to get this error when setting up the widget

<img width="765" alt="screen shot 2018-02-07 at 8 25 48 pm" src="https://user-images.githubusercontent.com/36250239/35950554-1b183430-0c45-11e8-9c6e-51ac4cacf51d.png">

I have node installed via brew yet I get this page every time I refresh Übersicht.

Yes, I downloaded WunderlistTasksWidget.zip, not the source code. I unzipped it and put it in the Übersicht widget directory. 

I get this page after I sign into Wunderlist.

**Comment by Makiah** [comment]
Hmmm... another user mentioned something similar.  Would you mind pasting your Übersicht log?  You can find it like so: 
![image](https://user-images.githubusercontent.com/10727824/35980908-e54ad41e-0cb9-11e8-910d-cd7449d4f15f.png)

**Comment by Kamorini** [comment]
<img width="815" alt="screen shot 2018-02-08 at 5 57 44 pm" src="https://user-images.githubusercontent.com/36250239/36002840-9db53442-0cf9-11e8-8d7e-bbf0438f99a5.png">

Thanks

**Comment by Makiah** [comment]
Is your datadisplayer.js file located in ```/Library/Application Support/Übersicht/widgets/WunderlistTasksWidget/lib/datadisplay/datadisplayer.js```?

If so, could you navigate to that folder and run ```node datadisplayer.js```?  If you then leave the file running and go to http://127.0.0.1 in your browser, you should see some output displayed (regardless of whether it's an error).  If not, I guess it might be an issue with node.

**Comment by Kamorini** [comment]
Thank you for your responsiveness, I will be excited if you can help me to get this to work. 
And I'm sorry if I don't know exactly what I'm doing, I'm not that familiar with terminal.

This is what happened
<img width="1368" alt="screen shot 2018-02-09 at 4 40 49 pm" src="https://user-images.githubusercontent.com/36250239/36051588-9dea9618-0db8-11e8-8cde-77efa8312a15.png">

Thank you

**Comment by Makiah** [comment]
Ok, so node seems to be working fine, so I'm confused as to why it's not showing up for you.  If you run ```/Library/Application Support/Übersicht/widgets/WunderlistTasksWidget/lib/oauthserver/server.js``` and then try to run the app, does it say "Thanks!" and then close the tab?

**Comment by Makiah** [comment]
(By running the app, I'm referring to just un-hiding the widget)

**Comment by Kamorini** [comment]
I ran `node server.js` after navigating to `/Library/Application Support/Übersicht/widgets/WunderlistTasksWidget/lib/oauthserver` and got this

<img width="649" alt="screen shot 2018-02-14 at 9 13 11 am" src="https://user-images.githubusercontent.com/36250239/36208661-9e1493ac-1167-11e8-82f5-996ee0755aad.png">

It was undefined until I unhid the widget

Then a window opened saying  **Thanks!**
and then the tab closed shortly after that

**Comment by Kamorini** [comment]
I also get this on my desktop, presumably where the widget is. This only happens once after I refresh my widgets. It goes away after any other refreshes unless I run `node server.js` again.

<img width="353" alt="screen shot 2018-02-14 at 9 22 03 am" src="https://user-images.githubusercontent.com/36250239/36209019-977f85b4-1168-11e8-9728-89c1b13aef72.png">

Thanks in advance

**Comment by Makiah** [comment]
I just pushed b511f59, which might solve your issue: I changed the node path from /usr/local/Cellar/node to /usr/local/bin/node (since it seems as though your 8.4.9 install doesn't include the node binary).

**Comment by Kamorini** [comment]
So I no longer get the __"Safari can't connect to server"__ issue. When I refresh my widgets I get the popup for wunderlist that redirects to the page saying  __"Thanks"__. The problem is that nothing displays on my desktop. 

I'm not sure if it is related but I get this error in the Debug Console for Übersicht
<img width="848" alt="screen shot 2018-02-14 at 5 24 17 pm" src="https://user-images.githubusercontent.com/36250239/36231408-eac7665e-11ab-11e8-8f42-8b2135d67e60.png">

**Comment by Makiah** [comment]
I've seen that happen a couple times with Ubersicht, if you "Refresh all Widgets" does the issue persist?

**Comment by Kamorini** [comment]
Last night no matter how many times I refreshed the widgets it wouldn't work. But I woke up this morning to see a working Wunderlist widget on my desktop.

Thank You so much for helping me solve this issue. I really appreciate it. 🙏

**Comment by Kamorini** [comment]
Ok, I just closed out of iCalender and it caused my widgets to refresh. This happens often and I think it is a side effect of Übersicht's coding. However when it refreshed the Wunderlist Widget did not appear. It somehow was not selected to appear on my Built-in display, and I think this was the problem I was having earlier.

**Comment by Makiah** [comment]
That's great news!  Tell me if you have any other issues with it.
