### ISSUE TITLE
Display specific lists only

### ISSUE THREAD

**Issue by GizmoBen** [Makiah/WunderlistTasksWidget#4]
Hello,

I don't have any knowledge in Javascript so my modifications are not working, I would like to be able to display only specific lists, the work related ones on my desktop. If I'm correct, it is decided in the datadisplayer.js in a loop that scroll through all the lists with list_id but I don't know how to modify it so that it displays only a certain number of lists... I tried to read Wunderlist API and list.id are integer in it but I sadly could not make it work so I'm asking for your help if it is not too much work to tell me how to manage my lists ;-)

Thank you for your work, the widget works great by the way !

**Comment by Makiah** [comment]
I'm glad it's been working for you!  I just added that functionality in b511f59, check out "Configurable Features" in the ReadMe for instructions on how to filter lists by title.

**Comment by GizmoBen** [comment]
It’s working perfectly !!! Thank you so much and thank you for your reactivity, keep up the good work !!!

Benjamin
