### ISSUE TITLE
Tasks  without  date not displayed

### ISSUE THREAD

**Issue by vk996** [Makiah/WunderlistTasksWidget#5]
Hi, your app very cool but tasks without date not displayed.

**Comment by Makiah** [comment]
Currently, the widget will only display tasks it classifies as "urgent": those which are due soon.  Would you like this to be a feature?  I could probably add a configuration setting to enable that.

**Comment by vk996** [comment]
It will be cool if you can add this option.
Thanks

**Comment by Makiah** [comment]
It'll probably take me a while to get to it, but I'll try to get something out.  Thanks for the suggestion!

**Comment by Makiah** [comment]
Added support for tasks without dates in 3a40bb6, release v0.3 (https://github.com/Makiah/WunderlistTasksWidget/releases).
