### ISSUE TITLE
Can't get widget to display tasks

### ISSUE THREAD

**Issue by eemuayd** [Makiah/WunderlistTasksWidget#6]
Hello,

Disclaimer: I tried to follow instructions to the best of my ability, might've done it wrong.

- Übersicht installed
- Widget downloaded and placed in Übersicht folder

Then I installed node.js and was prompted to enter wunderlist credentials, and I did and it says "Thanks", however, nothing shows up on the desktop except for the logo and white banner behind it.

I appreciate any help, and thanks in advance!

**Comment by eemuayd** [comment]
Hi @Makiah apologies for bothering, could you please take a look at this issue.

Thank you!

**Comment by Makiah** [comment]
Thanks for the reminder!  Sorry for late response: busy week. Would you mind pasting a pic of the ubersicht logs?  You can access it from the icon in your task bar.

**Comment by eemuayd** [comment]
Thanks for the response,

I restarted ubersicht and there's a lot of those:

![Logs](https://user-images.githubusercontent.com/23260032/41509741-412009c8-7261-11e8-92d0-b198d439a107.png)

I hope this helps

**Comment by Makiah** [comment]
Are your tasks set to be completed within the next couple days?  If not, would you make a task on your ubersicht dashboard due tomorrow and see whether that shows up?

**Comment by eemuayd** [comment]
I don't use due dates, however added a due date and it showed up! Yay! :)
Btw, is there a way to show tasks that don't have a due date?

Apologies for the inconvenience and thank you for your time @Makiah!

Cheers!

**Comment by Makiah** [comment]
Yeah I should definitely add an option to show tasks that don't have a due date, I think that #5 mentions this at well.  I'll work on that ASAP.  Glad I could help though!

**Comment by eemuayd** [comment]
It's definitely not an issue, still an awesome and beautiful widget, thanks for making!

**Comment by Makiah** [comment]
Added support for tasks without dates in 3a40bb6, release v0.3 (https://github.com/Makiah/WunderlistTasksWidget/releases).  Lmk when you test and if any additional bugfixes would be useful!

**Comment by eemuayd** [comment]
Just tested it out, it's perfect!

Thank you @Makiah

**Comment by eemuayd** [comment]
Hi @Makiah,

So after using the widget for a couple of hours I noticed:
- Lists swap positions on screen every few mins
- Location on screen doesn't change after modifying style (top, left, width and height)
- Can't change `var includeLists = customizationJSON["lists-to-display"];` to show specific lists and hide others

I did not submit an issue since I'm ok with the way it is now (or I just simply messed something up), however, I thought I might share in case someone else faces the same issues

Cheers and thanks!

**Comment by Makiah** [comment]
Hi @eemuayd!  Thanks for the feedback.  

The list swapping is something I've also noticed and can fix (unfortunately it's a bit annoying to complete so I've avoided it thus far).  

For your latter two issues, are you sure you're changing the `customization.json` file correctly?  In the latest release, you shouldn't have to touch any javascript files on your own.  If you only want to display two subjects, here's an example: 
```
{
    "positioning": {
        "left-offset-percentage": 59,
        "top-offset-percentage": 5,     
        "width-percentage": 32.5,      
        "height-percentage": 90       
    }, 
    "lists-to-display": [
        "My First List", 
        "My Second List"
    ], 
    "urgency-filters": {
        "display-tasks-without-due-date": true,  
        "display-tasks-due-within-x-days": 7     
    }
}
```

Also, note that Übersicht has to update before the positioning changes.  Would you send me your customization file if it still doesn't work?

**Comment by Makiah** [comment]
Oh, I forgot to mention that you might have to get rid of the comments in the JSON before you paste it in.  I'll update the readme to reflect that.

**Comment by eemuayd** [comment]
Got it, I was editing the index file, and the datadisplayer.js. I made the position changes on customization.json and all I need is one list, so that gets rid of the swapping issue for me :)

All good, thank you sir!

**Comment by Makiah** [comment]
Awesome!  Glad it helped.
